# Generated by Django 5.0.14 on 2025-09-24 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "formularios_categoria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("permitir_fotos", models.BooleanField(default=False)),
                ("permitir_gps", models.BooleanField(default=False)),
                ("disponible_desde_fecha", models.DateField()),
                ("disponible_hasta_fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Ingresada", "Ingresada"),
                            ("Activa", "Activa"),
                            ("Suspendida", "Suspendida"),
                            ("Pruebas", "Pruebas"),
                            ("Anulada", "Anulada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forma_envio",
                    models.CharField(
                        choices=[
                            ("En Linea/fuera Linea", "En Linea/fuera Linea"),
                            ("En Linea", "En Linea"),
                            ("Guardar", "Guardar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("es_publico", models.BooleanField(default=False)),
                ("auto_envio", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "formularios_formulario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "formularios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_rol_formulario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_rol_formulario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.CharField(max_length=128)),
                ("nombre_usuario", models.CharField(max_length=50, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "formularios_usuario",
                "managed": False,
            },
        ),
    ]
