# Generated by Django 5.2.2 on 2025-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="pertenece_grupo",
            field=models.BooleanField(
                default=False, help_text="Indica si este campo pertenece a un grupo."
            ),
        ),
        migrations.AddField(
            model_name="campo",
            name="tipo_grupo",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este campo representa un grupo (campo tipo grupo).",
            ),
        ),
    ]
