# Generated by Django 5.0.14 on 2025-09-24 02:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulario_Index_Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_formularios_index_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FormularioIndexVersion",
            fields=[
                (
                    "id_index_version",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "formularios_formularioindexversion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id_pagina",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secuencia", models.PositiveIntegerField(default=1)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "formularios_pagina",
                "ordering": ["secuencia"],
                "managed": False,
            },
        ),
    ]
