# Generated by Django 5.0.14 on 2025-07-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Ingresada", "Ingresada"),
                    ("Activa", "Activa"),
                    ("Suspendida", "Suspendida"),
                    ("Pruebas", "Pruebas"),
                    ("Anulada", "Anulada"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="forma_envio",
            field=models.CharField(
                choices=[
                    ("En Linea/fuera Linea", "En Linea/fuera Linea"),
                    ("En Linea", "En Linea"),
                    ("Guardar", "Guardar"),
                ],
                max_length=30,
            ),
        ),
    ]
