# Generated by Django 5.0.14 on 2025-09-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
