# Generated by Django 5.0.14 on 2025-10-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id_grupo",
                    models.CharField(
                        db_column="id_grupo",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=150)),
                (
                    "id_campo_group",
                    models.OneToOneField(
                        db_column="id_campo_group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo",
                        to="formularios.campo",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_grupo",
            },
        ),
        migrations.CreateModel(
            name="CampoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_campo",
                    models.ForeignKey(
                        db_column="id_campo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="formularios.campo",
                    ),
                ),
                (
                    "id_grupo",
                    models.ForeignKey(
                        db_column="id_grupo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="formularios.grupo",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_campo_grupo",
                "unique_together": {("id_grupo", "id_campo")},
            },
        ),
    ]
