# Generated by Django 5.2.2 on 2025-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_campo_pertenece_grupo_campo_tipo_grupo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campo",
            name="tipo_grupo",
        ),
        migrations.AlterField(
            model_name="campo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("numero", "Número"),
                    ("fecha", "Fecha"),
                    ("booleano", "Booleano"),
                    ("grupo", "Grupo"),
                ],
                max_length=20,
            ),
        ),
    ]
