# Generated by Django 5.0.14 on 2025-09-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_usuario_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
