# Generated by Django 5.0.14 on 2025-09-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formularios",
            "0002_formulario_index_version_formularioindexversion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Campo",
            fields=[
                (
                    "id_campo",
                    models.CharField(
                        db_column="id_campo",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(db_column="tipo", max_length=20)),
                ("clase", models.CharField(db_column="clase", max_length=30)),
                (
                    "nombre_campo",
                    models.CharField(db_column="nombre_campo", max_length=64),
                ),
                ("etiqueta", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "ayuda",
                    models.CharField(
                        blank=True, db_column="ayuda", max_length=255, null=True
                    ),
                ),
                ("config", models.TextField(blank=True, db_column="config", null=True)),
                ("requerido", models.BooleanField(db_column="requerido", null=True)),
            ],
            options={
                "db_table": "formularios_campo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClaseCampo",
            fields=[
                (
                    "clase",
                    models.CharField(
                        db_column="clase",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estructura",
                    models.TextField(blank=True, db_column="estructura", null=True),
                ),
            ],
            options={
                "db_table": "formularios_clase_campo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pagina_Index_Version",
            fields=[
                (
                    "id_pagina",
                    models.OneToOneField(
                        db_column="id_pagina",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="puntero_version",
                        serialize=False,
                        to="formularios.pagina",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_pagina_index_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaginaVersion",
            fields=[
                (
                    "id_pagina_version",
                    models.CharField(
                        db_column="id_pagina_version",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(db_column="fecha_creacion")),
                (
                    "id_pagina",
                    models.CharField(db_column="id_pagina", max_length=32, null=True),
                ),
            ],
            options={
                "db_table": "formularios_pagina_version",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="roluser",
            table="formularios_rol_user",
        ),
        migrations.CreateModel(
            name="PaginaCampo",
            fields=[
                (
                    "id_campo",
                    models.ForeignKey(
                        db_column="id_campo",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="enlaces_pagina",
                        serialize=False,
                        to="formularios.campo",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(db_column="sequence", null=True),
                ),
            ],
            options={
                "db_table": "formularios_pagina_campo",
                "managed": False,
            },
        ),
    ]
