# Generated by Django 5.0.14 on 2025-10-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_grupo_campogrupo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userformulario",
            unique_together={("id_formulario", "id_usuario")},
        ),
        migrations.AddIndex(
            model_name="userformulario",
            index=models.Index(
                fields=["id_usuario", "id_formulario"],
                name="formularios_id_usua_73941f_idx",
            ),
        ),
    ]
