# Generated by Django 5.0.14 on 2025-10-09 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0003_alter_userformulario_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuenteDatosVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("row_count", models.IntegerField(default=0)),
                ("columnas", models.JSONField(default=list)),
                ("content_hash", models.CharField(max_length=64)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="formularios.fuentedatos",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_fuente_datos_version",
                "unique_together": {("fuente", "version")},
            },
        ),
        migrations.CreateModel(
            name="FuenteDatosValor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("columna", models.CharField(max_length=200)),
                ("key_text", models.TextField(blank=True, null=True)),
                ("label_text", models.TextField()),
                ("valor_raw", models.JSONField(default=dict)),
                ("extras", models.JSONField(default=dict)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="formularios.fuentedatosversion",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_fuente_datos_valor",
                "indexes": [
                    models.Index(
                        fields=["version", "columna"],
                        name="formularios_version_e004fe_idx",
                    )
                ],
                "unique_together": {("version", "columna", "key_text", "label_text")},
            },
        ),
    ]
