# Generated by Django 5.0.14 on 2025-08-12 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_rename_id_formularioindexversion_id_index_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id_pagina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('color_fondo', models.CharField(blank=True, max_length=20)),
                ('color_texto', models.CharField(blank=True, max_length=20)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='formularios.formulario')),
                ('index_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='formularios.formularioindexversion')),
            ],
            options={
                'ordering': ['secuencia'],
            },
        ),
        migrations.CreateModel(
            name='PaginaIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.formulario')),
                ('id_index_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_index', to='formularios.formularioindexversion')),
                ('id_pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='formularios.pagina')),
            ],
            options={
                'unique_together': {('id_index_version', 'id_pagina')},
            },
        ),
    ]
