# Generated by Django 5.0.14 on 2025-09-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("formularios", "0003_usuario_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="formularios_usuarios",
                related_query_name="formularios_usuario",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="formularios_usuarios",
                related_query_name="formularios_usuario",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
