# Generated by Django 5.2.2 on 2025-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0003_remove_campo_tipo_grupo_alter_campo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campo",
            name="pertenece_grupo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="campo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("numero", "Número"),
                    ("fecha", "Fecha"),
                    ("booleano", "Booleano"),
                ],
                max_length=20,
            ),
        ),
    ]
