# Generated by Django 5.0.14 on 2025-10-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0004_fuentedatosversion_fuentedatosvalor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fuentedatosvalor",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fuentedatosvalor",
            name="campo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_valores",
                to="formularios.campo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fuentedatosvalor",
            unique_together={("campo", "key_text", "label_text")},
        ),
        migrations.AddIndex(
            model_name="fuentedatosvalor",
            index=models.Index(
                fields=["campo", "label_text"], name="formularios_campo_i_254189_idx"
            ),
        ),
    ]
