# Generated by Django 5.0.14 on 2025-08-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0005_clasecampo_campo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clasecampo",
            name="descripcion",
        ),
    ]
