# Generated by Django 5.2.9 on 2025-12-04 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formularios",
            "0006_remove_paginaversion_formularios_index_v_1e54e0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fuentedatos",
            name="tipo_fuente",
            field=models.CharField(
                choices=[("archivo", "Archivo (Excel/CSV)"), ("sql", "Consulta SQL")],
                default="archivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fuentedatos",
            name="archivo_nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fuentedatos",
            name="blob_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="fuentedatos",
            name="blob_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="fuentedatos",
            name="tipo_archivo",
            field=models.CharField(
                blank=True,
                choices=[("excel", "Excel"), ("csv", "CSV")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ConexionSQL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo de la conexión", max_length=200
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_bd",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlserver", "SQL Server"),
                            ("oracle", "Oracle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("puerto", models.IntegerField()),
                ("database", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=100)),
                ("password_encrypted", models.BinaryField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("opciones_extra", models.JSONField(blank=True, default=dict)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conexiones_sql",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "formularios_conexion_sql",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConsultaSQL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "query_sql",
                    models.TextField(help_text="Query SQL (solo SELECT permitido)"),
                ),
                (
                    "columna_value",
                    models.CharField(
                        help_text="Columna que se usará como 'value'", max_length=100
                    ),
                ),
                (
                    "columna_label",
                    models.CharField(
                        help_text="Columna que se usará como 'label'", max_length=100
                    ),
                ),
                (
                    "columnas_extra",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Columnas adicionales a incluir",
                    ),
                ),
                (
                    "cache_minutos",
                    models.IntegerField(
                        default=60, help_text="Tiempo de cache en minutos"
                    ),
                ),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("resultado_cache", models.JSONField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "conexion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="formularios.conexionsql",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_sql",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "formularios_consulta_sql",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="fuentedatos",
            name="consulta_sql",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuentes_datos",
                to="formularios.consultasql",
            ),
        ),
    ]
