# Generated by Django 5.0.14 on 2025-08-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0006_remove_clasecampo_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clasecampo",
            old_name="name",
            new_name="clase",
        ),
    ]
