# Generated by Django 5.0.14 on 2025-09-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0008_formularioactualversion_paginaactualversion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paginaactualversion",
            options={"ordering": ["formulario_id", "pagina__secuencia"]},
        ),
        migrations.RemoveIndex(
            model_name="paginaactualversion",
            name="formularios_formula_cd75e9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="paginaactualversion",
            unique_together={("version_activa", "pagina")},
        ),
        migrations.AddIndex(
            model_name="paginaactualversion",
            index=models.Index(
                fields=["formulario"], name="formularios_formula_940d64_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="paginaactualversion",
            name="orden",
        ),
    ]
