# Generated by Django 5.2.9 on 2025-12-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0008_remove_consultasql_columna_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTerminal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "terminal_info",
                    models.TextField(
                        help_text="Información del terminal/dispositivo (JSON, user agent, etc.)"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de registro del terminal"
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminal de Usuario",
                "verbose_name_plural": "Terminales de Usuario",
                "db_table": "formularios_user_terminal",
                "ordering": ["-date"],
                "managed": False,
            },
        ),
    ]
