# Generated by Django 5.2.9 on 2025-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_userterminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularioentry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='userterminal',
            options={'ordering': ['-date'], 'verbose_name': 'Terminal de Usuario', 'verbose_name_plural': 'Terminales de Usuario'},
        ),
        migrations.AlterField(
            model_name='conexionsql',
            name='database',
            field=models.CharField(blank=True, default='', help_text='Nombre de la base de datos', max_length=200),
        ),
    ]
