# Generated by Django 5.2.9 on 2026-01-30 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_alter_formularioentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userterminal',
            name='nombre_usuario',
            field=models.ForeignKey(blank=True, db_column='nombre_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to=settings.AUTH_USER_MODEL),
        ),
    ]
