# Generated by Django 5.0.14 on 2025-09-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0012_alter_campo_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcampos",
                to="formularios.campo",
            ),
        ),
        migrations.AddIndex(
            model_name="campo",
            index=models.Index(
                fields=["pagina", "grupo", "sequence"],
                name="formularios_pagina__2fea0f_idx",
            ),
        ),
    ]
