# Generated by Django 5.0.14 on 2025-09-09 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0014_remove_usuario_rol_delete_rol_delete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.CharField(max_length=128)),
                ("nombre_usuario", models.CharField(max_length=50, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="formularios.rol",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_usuario",
            },
        ),
    ]
