# Generated by Django 5.0.14 on 2025-07-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_alter_formulario_estado_alter_formulario_forma_envio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formularioindexversion",
            old_name="id",
            new_name="id_index_version",
        ),
        migrations.RemoveField(
            model_name="formulario",
            name="fecha_creacion",
        ),
    ]
