# Generated by Django 5.0.14 on 2025-08-29 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0004_pagina_paginaindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaseCampo",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("schema", models.JSONField(blank=True, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "formularios_clase_campo2",
            },
        ),
        migrations.CreateModel(
            name="Campo",
            fields=[
                (
                    "id_campo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("clase", models.CharField(max_length=20)),
                ("nombre_campo", models.CharField(max_length=120)),
                ("etiqueta", models.CharField(max_length=200)),
                ("ayuda", models.CharField(blank=True, default="", max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("requerido", models.BooleanField(default=False)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="formularios.pagina",
                    ),
                ),
            ],
            options={
                "db_table": "formularios_campo2",
                "ordering": ["sequence", "id_campo"],
                "indexes": [
                    models.Index(
                        fields=["pagina", "sequence"],
                        name="formularios_pagina__6cb394_idx",
                    ),
                    models.Index(
                        fields=["pagina", "nombre_campo"],
                        name="formularios_pagina__49a114_idx",
                    ),
                    models.Index(fields=["clase"], name="formularios_clase_9a93f0_idx"),
                ],
                "unique_together": {("pagina", "nombre_campo")},
            },
        ),
    ]
