# Generated by Django 5.0.14 on 2025-09-01 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0007_rename_name_clasecampo_clase"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioActualVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("publicada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "formulario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_activa",
                        to="formularios.formulario",
                    ),
                ),
                (
                    "index_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_activas",
                        to="formularios.formularioindexversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaginaActualVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("fecha_creacion", models.DateTimeField()),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas_actuales",
                        to="formularios.formulario",
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_actuales",
                        to="formularios.pagina",
                    ),
                ),
                (
                    "version_activa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas_actuales",
                        to="formularios.formularioactualversion",
                    ),
                ),
            ],
            options={
                "ordering": ["formulario_id", "orden"],
            },
        ),
        migrations.CreateModel(
            name="PaginaCampoActual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("requerido", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_actuales",
                        to="formularios.campo",
                    ),
                ),
                (
                    "pagina_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos_actuales",
                        to="formularios.paginaactualversion",
                    ),
                ),
            ],
            options={
                "ordering": ["pagina_actual_id", "orden"],
            },
        ),
        migrations.AddIndex(
            model_name="paginaactualversion",
            index=models.Index(
                fields=["formulario", "orden"], name="formularios_formula_cd75e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paginaactualversion",
            index=models.Index(
                fields=["version_activa"], name="formularios_version_ad8a96_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paginaactualversion",
            unique_together={("formulario", "orden"), ("version_activa", "pagina")},
        ),
        migrations.AddIndex(
            model_name="paginacampoactual",
            index=models.Index(
                fields=["pagina_actual", "orden"], name="formularios_pagina__8e5c69_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paginacampoactual",
            unique_together={("pagina_actual", "campo"), ("pagina_actual", "orden")},
        ),
    ]
