# Generated by Django 5.0.14 on 2025-09-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0010_fix_delete_cascade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paginaactualversion",
            options={"ordering": ["formulario_id"]},
        ),
    ]
