# Generated by Django 5.0.14 on 2025-09-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0011_alter_paginaactualversion_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="campo",
            unique_together=set(),
        ),
    ]
