# Generated by Django 5.0.14 on 2025-09-09 10:05
from django.db import migrations

SQL = r"""
IF OBJECT_ID(N'[dbo].[formularios_usuario]', N'U') IS NOT NULL
BEGIN
    -- Si existe FK/Índice del campo 'rol', se eliminan de forma segura
    -- Descubre el nombre exacto de la FK si aplica; como genérico:
    -- ALTER TABLE [dbo].[formularios_usuario] DROP CONSTRAINT [FK_formularios_usuario_rol] ;
    IF COL_LENGTH('dbo.formularios_usuario', 'rol_id') IS NOT NULL
    BEGIN
        -- Elimina FK por nombre si lo conoces; si no, podrías buscarla dinámicamente.
        -- Luego elimina la columna:
        ALTER TABLE [dbo].[formularios_usuario] DROP COLUMN [rol_id];
    END
END

IF OBJECT_ID(N'[dbo].[formularios_usuario]', N'U') IS NOT NULL
    DROP TABLE [dbo].[formularios_usuario];
"""

class Migration(migrations.Migration):
    dependencies = [
        ('formularios', '0013_campo_grupo_campo_formularios_pagina__2fea0f_idx'), 
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # Quita modelos/fields del estado para que Django no los vea
                migrations.DeleteModel(name='Usuario'),
            ],
        ),
    ]