--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2026-01-29 23:06:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16413)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16412)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16421)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16420)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16407)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16406)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 16721)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id character varying(50) NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 16720)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16399)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16398)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16391)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16390)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 16970)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16452)
-- Name: formularios_campo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_campo (
    id_campo uuid NOT NULL,
    tipo character varying(20) NOT NULL,
    clase character varying(30) NOT NULL,
    nombre_campo character varying(64) NOT NULL,
    etiqueta character varying(100) NOT NULL,
    ayuda character varying(255),
    config text,
    requerido boolean
);


ALTER TABLE public.formularios_campo OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16546)
-- Name: formularios_campo_grupo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_campo_grupo (
    id bigint NOT NULL,
    id_campo uuid NOT NULL,
    id_grupo uuid NOT NULL
);


ALTER TABLE public.formularios_campo_grupo OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16545)
-- Name: formularios_campo_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formularios_campo_grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formularios_campo_grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16459)
-- Name: formularios_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_categoria (
    id uuid NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.formularios_categoria OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16466)
-- Name: formularios_clase_campo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_clase_campo (
    clase character varying(30) NOT NULL,
    estructura text
);


ALTER TABLE public.formularios_clase_campo OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 16762)
-- Name: formularios_conexion_sql; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_conexion_sql (
    id uuid NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    tipo_bd character varying(20) NOT NULL,
    host character varying(255) NOT NULL,
    puerto integer NOT NULL,
    database character varying(200) NOT NULL,
    usuario character varying(100) NOT NULL,
    password_encrypted bytea NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    opciones_extra jsonb NOT NULL,
    creado_por_id character varying(50)
);


ALTER TABLE public.formularios_conexion_sql OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 16769)
-- Name: formularios_consulta_sql; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_consulta_sql (
    id uuid NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    query_sql text NOT NULL,
    cache_minutos integer NOT NULL,
    ultima_ejecucion timestamp with time zone,
    resultado_cache jsonb,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    conexion_id uuid NOT NULL,
    creado_por_id character varying(50)
);


ALTER TABLE public.formularios_consulta_sql OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16499)
-- Name: formularios_formulario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_formulario (
    id uuid NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    permitir_fotos boolean NOT NULL,
    permitir_gps boolean NOT NULL,
    disponible_desde_fecha date NOT NULL,
    disponible_hasta_fecha date NOT NULL,
    estado character varying(20) NOT NULL,
    forma_envio character varying(30) NOT NULL,
    es_publico boolean NOT NULL,
    auto_envio boolean NOT NULL,
    categoria_id uuid,
    periodicidad integer
);


ALTER TABLE public.formularios_formulario OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16506)
-- Name: formularios_formularioindexversion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_formularioindexversion (
    id_index_version uuid NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL
);


ALTER TABLE public.formularios_formularioindexversion OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16533)
-- Name: formularios_formularios_index_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_formularios_index_version (
    id_index_version uuid NOT NULL,
    id_formulario uuid NOT NULL
);


ALTER TABLE public.formularios_formularios_index_version OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16511)
-- Name: formularios_fuente_datos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_fuente_datos (
    id uuid NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    archivo_nombre character varying(255),
    blob_name character varying(500),
    blob_url character varying(1000),
    tipo_archivo character varying(10),
    columnas jsonb NOT NULL,
    preview_data jsonb NOT NULL,
    fecha_subida timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    creado_por_id character varying(50),
    tipo_fuente character varying(20) NOT NULL,
    consulta_sql_id uuid
);


ALTER TABLE public.formularios_fuente_datos OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16538)
-- Name: formularios_fuente_datos_valor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_fuente_datos_valor (
    id uuid NOT NULL,
    columna character varying(200) NOT NULL,
    key_text text,
    label_text text NOT NULL,
    valor_raw jsonb NOT NULL,
    extras jsonb NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    campo_id uuid NOT NULL,
    fuente_id uuid NOT NULL
);


ALTER TABLE public.formularios_fuente_datos_valor OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16518)
-- Name: formularios_grupo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_grupo (
    id_grupo uuid NOT NULL,
    nombre character varying(150) NOT NULL,
    id_campo_group uuid NOT NULL
);


ALTER TABLE public.formularios_grupo OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16525)
-- Name: formularios_pagina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_pagina (
    id_pagina uuid NOT NULL,
    secuencia integer NOT NULL,
    nombre character varying(120) NOT NULL,
    descripcion text NOT NULL,
    CONSTRAINT formularios_pagina_secuencia_check CHECK ((secuencia >= 0))
);


ALTER TABLE public.formularios_pagina OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16562)
-- Name: formularios_pagina_campo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_pagina_campo (
    id_campo uuid NOT NULL,
    sequence integer,
    id_pagina_version character varying(32) NOT NULL,
    CONSTRAINT formularios_pagina_campo_sequence_check CHECK ((sequence >= 0))
);


ALTER TABLE public.formularios_pagina_campo OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16551)
-- Name: formularios_pagina_index_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_pagina_index_version (
    id_pagina uuid NOT NULL,
    id_index_version uuid NOT NULL
);


ALTER TABLE public.formularios_pagina_index_version OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16473)
-- Name: formularios_pagina_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_pagina_version (
    id_pagina_version character varying(32) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    id_pagina uuid
);


ALTER TABLE public.formularios_pagina_version OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16557)
-- Name: formularios_user_formulario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_user_formulario (
    id bigint NOT NULL,
    id_formulario_id uuid NOT NULL,
    id_usuario_id character varying(50) NOT NULL
);


ALTER TABLE public.formularios_user_formulario OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16556)
-- Name: formularios_user_formulario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formularios_user_formulario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formularios_user_formulario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 16812)
-- Name: formularios_user_terminal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_user_terminal (
    id bigint NOT NULL,
    terminal_info text NOT NULL,
    date timestamp with time zone NOT NULL,
    nombre_usuario character varying(50)
);


ALTER TABLE public.formularios_user_terminal OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 16811)
-- Name: formularios_user_terminal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formularios_user_terminal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formularios_user_terminal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16478)
-- Name: formularios_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_usuario (
    last_login timestamp with time zone,
    nombre_usuario character varying(50) NOT NULL,
    nombre character varying(100) NOT NULL,
    correo character varying(254) NOT NULL,
    password character varying(128) NOT NULL,
    activo boolean NOT NULL,
    acceso_web boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.formularios_usuario OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16488)
-- Name: formularios_usuario_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_usuario_groups (
    id bigint NOT NULL,
    usuario_id character varying(50) NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.formularios_usuario_groups OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16487)
-- Name: formularios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formularios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formularios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16494)
-- Name: formularios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formularios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id character varying(50) NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.formularios_usuario_user_permissions OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16493)
-- Name: formularios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formularios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formularios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 16837)
-- Name: oauth2_provider_accesstoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth2_provider_accesstoken (
    id bigint NOT NULL,
    token text NOT NULL,
    expires timestamp with time zone NOT NULL,
    scope text NOT NULL,
    application_id bigint,
    user_id character varying(50),
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    source_refresh_token_id bigint,
    id_token_id bigint,
    token_checksum character varying(64) NOT NULL
);


ALTER TABLE public.oauth2_provider_accesstoken OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 16836)
-- Name: oauth2_provider_accesstoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth2_provider_accesstoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth2_provider_accesstoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 16827)
-- Name: oauth2_provider_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth2_provider_application (
    id bigint NOT NULL,
    client_id character varying(100) NOT NULL,
    redirect_uris text NOT NULL,
    client_type character varying(32) NOT NULL,
    authorization_grant_type character varying(32) NOT NULL,
    client_secret character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    user_id character varying(50),
    skip_authorization boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    algorithm character varying(5) NOT NULL,
    post_logout_redirect_uris text NOT NULL,
    hash_client_secret boolean NOT NULL,
    allowed_origins text NOT NULL
);


ALTER TABLE public.oauth2_provider_application OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 16826)
-- Name: oauth2_provider_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth2_provider_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth2_provider_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 16847)
-- Name: oauth2_provider_grant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth2_provider_grant (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL,
    redirect_uri text NOT NULL,
    scope text NOT NULL,
    application_id bigint NOT NULL,
    user_id character varying(50) NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    code_challenge character varying(128) NOT NULL,
    code_challenge_method character varying(10) NOT NULL,
    nonce character varying(255) NOT NULL,
    claims text NOT NULL
);


ALTER TABLE public.oauth2_provider_grant OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 16846)
-- Name: oauth2_provider_grant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth2_provider_grant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth2_provider_grant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 16933)
-- Name: oauth2_provider_idtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth2_provider_idtoken (
    id bigint NOT NULL,
    jti uuid NOT NULL,
    expires timestamp with time zone NOT NULL,
    scope text NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    application_id bigint,
    user_id character varying(50)
);


ALTER TABLE public.oauth2_provider_idtoken OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 16932)
-- Name: oauth2_provider_idtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth2_provider_idtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth2_provider_idtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 16857)
-- Name: oauth2_provider_refreshtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth2_provider_refreshtoken (
    id bigint NOT NULL,
    token character varying(255) NOT NULL,
    access_token_id bigint,
    application_id bigint NOT NULL,
    user_id character varying(50) NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    revoked timestamp with time zone,
    token_family uuid
);


ALTER TABLE public.oauth2_provider_refreshtoken OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 16856)
-- Name: oauth2_provider_refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth2_provider_refreshtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth2_provider_refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5253 (class 0 OID 16413)
-- Dependencies: 224
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5255 (class 0 OID 16421)
-- Dependencies: 226
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5251 (class 0 OID 16407)
-- Dependencies: 222
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add campo	5	add_campo
18	Can change campo	5	change_campo
19	Can delete campo	5	delete_campo
20	Can view campo	5	view_campo
21	Can add categoria	6	add_categoria
22	Can change categoria	6	change_categoria
23	Can delete categoria	6	delete_categoria
24	Can view categoria	6	view_categoria
25	Can add clase campo	7	add_clasecampo
26	Can change clase campo	7	change_clasecampo
27	Can delete clase campo	7	delete_clasecampo
28	Can view clase campo	7	view_clasecampo
29	Can add pagina version	8	add_paginaversion
30	Can change pagina version	8	change_paginaversion
31	Can delete pagina version	8	delete_paginaversion
32	Can view pagina version	8	view_paginaversion
33	Can add usuario	9	add_usuario
34	Can change usuario	9	change_usuario
35	Can delete usuario	9	delete_usuario
36	Can view usuario	9	view_usuario
37	Can add formulario	10	add_formulario
38	Can change formulario	10	change_formulario
39	Can delete formulario	10	delete_formulario
40	Can view formulario	10	view_formulario
41	Can add formulario index version	11	add_formularioindexversion
42	Can change formulario index version	11	change_formularioindexversion
43	Can delete formulario index version	11	delete_formularioindexversion
44	Can view formulario index version	11	view_formularioindexversion
45	Can add fuente datos	12	add_fuentedatos
46	Can change fuente datos	12	change_fuentedatos
47	Can delete fuente datos	12	delete_fuentedatos
48	Can view fuente datos	12	view_fuentedatos
49	Can add grupo	13	add_grupo
50	Can change grupo	13	change_grupo
51	Can delete grupo	13	delete_grupo
52	Can view grupo	13	view_grupo
53	Can add pagina	14	add_pagina
54	Can change pagina	14	change_pagina
55	Can delete pagina	14	delete_pagina
56	Can view pagina	14	view_pagina
57	Can add formulario_ index_ version	15	add_formulario_index_version
58	Can change formulario_ index_ version	15	change_formulario_index_version
59	Can delete formulario_ index_ version	15	delete_formulario_index_version
60	Can view formulario_ index_ version	15	view_formulario_index_version
61	Can add fuente datos valor	16	add_fuentedatosvalor
62	Can change fuente datos valor	16	change_fuentedatosvalor
63	Can delete fuente datos valor	16	delete_fuentedatosvalor
64	Can view fuente datos valor	16	view_fuentedatosvalor
65	Can add campo grupo	17	add_campogrupo
66	Can change campo grupo	17	change_campogrupo
67	Can delete campo grupo	17	delete_campogrupo
68	Can view campo grupo	17	view_campogrupo
69	Can add pagina_ index_ version	18	add_pagina_index_version
70	Can change pagina_ index_ version	18	change_pagina_index_version
71	Can delete pagina_ index_ version	18	delete_pagina_index_version
72	Can view pagina_ index_ version	18	view_pagina_index_version
73	Can add user formulario	19	add_userformulario
74	Can change user formulario	19	change_userformulario
75	Can delete user formulario	19	delete_userformulario
76	Can view user formulario	19	view_userformulario
77	Can add pagina campo	20	add_paginacampo
78	Can change pagina campo	20	change_paginacampo
79	Can delete pagina campo	20	delete_paginacampo
80	Can view pagina campo	20	view_paginacampo
81	Can add formulario entry	21	add_formularioentry
82	Can change formulario entry	21	change_formularioentry
83	Can delete formulario entry	21	delete_formularioentry
84	Can view formulario entry	21	view_formularioentry
85	Can add conexion sql	22	add_conexionsql
86	Can change conexion sql	22	change_conexionsql
87	Can delete conexion sql	22	delete_conexionsql
88	Can view conexion sql	22	view_conexionsql
89	Can add consulta sql	23	add_consultasql
90	Can change consulta sql	23	change_consultasql
91	Can delete consulta sql	23	delete_consultasql
92	Can view consulta sql	23	view_consultasql
93	Can add Terminal de Usuario	24	add_userterminal
94	Can change Terminal de Usuario	24	change_userterminal
95	Can delete Terminal de Usuario	24	delete_userterminal
96	Can view Terminal de Usuario	24	view_userterminal
97	Can add session	25	add_session
98	Can change session	25	change_session
99	Can delete session	25	delete_session
100	Can view session	25	view_session
101	Can add application	26	add_application
102	Can change application	26	change_application
103	Can delete application	26	delete_application
104	Can view application	26	view_application
105	Can add access token	27	add_accesstoken
106	Can change access token	27	change_accesstoken
107	Can delete access token	27	delete_accesstoken
108	Can view access token	27	view_accesstoken
109	Can add grant	28	add_grant
110	Can change grant	28	change_grant
111	Can delete grant	28	delete_grant
112	Can view grant	28	view_grant
113	Can add refresh token	29	add_refreshtoken
114	Can change refresh token	29	change_refreshtoken
115	Can delete refresh token	29	delete_refreshtoken
116	Can view refresh token	29	view_refreshtoken
117	Can add id token	30	add_idtoken
118	Can change id token	30	change_idtoken
119	Can delete id token	30	delete_idtoken
120	Can view id token	30	view_idtoken
\.


--
-- TOC entry 5279 (class 0 OID 16721)
-- Dependencies: 250
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5249 (class 0 OID 16399)
-- Dependencies: 220
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	formularios	campo
6	formularios	categoria
7	formularios	clasecampo
8	formularios	paginaversion
9	formularios	usuario
10	formularios	formulario
11	formularios	formularioindexversion
12	formularios	fuentedatos
13	formularios	grupo
14	formularios	pagina
15	formularios	formulario_index_version
16	formularios	fuentedatosvalor
17	formularios	campogrupo
18	formularios	pagina_index_version
19	formularios	userformulario
20	formularios	paginacampo
21	formularios	formularioentry
22	formularios	conexionsql
23	formularios	consultasql
24	formularios	userterminal
25	sessions	session
26	oauth2_provider	application
27	oauth2_provider	accesstoken
28	oauth2_provider	grant
29	oauth2_provider	refreshtoken
30	oauth2_provider	idtoken
\.


--
-- TOC entry 5247 (class 0 OID 16391)
-- Dependencies: 218
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-01-30 02:15:11.197628-06
2	contenttypes	0002_remove_content_type_name	2026-01-30 02:15:11.212-06
3	auth	0001_initial	2026-01-30 02:15:11.301378-06
4	auth	0002_alter_permission_name_max_length	2026-01-30 02:15:11.306537-06
5	auth	0003_alter_user_email_max_length	2026-01-30 02:15:11.31465-06
6	auth	0004_alter_user_username_opts	2026-01-30 02:15:11.324552-06
7	auth	0005_alter_user_last_login_null	2026-01-30 02:15:11.334076-06
8	auth	0006_require_contenttypes_0002	2026-01-30 02:15:11.335453-06
9	auth	0007_alter_validators_add_error_messages	2026-01-30 02:15:11.344352-06
10	auth	0008_alter_user_username_max_length	2026-01-30 02:15:11.353589-06
11	auth	0009_alter_user_last_name_max_length	2026-01-30 02:15:11.361634-06
12	auth	0010_alter_group_name_max_length	2026-01-30 02:15:11.370281-06
13	auth	0011_update_proxy_permissions	2026-01-30 02:15:11.377397-06
14	auth	0012_alter_user_first_name_max_length	2026-01-30 02:15:11.383331-06
15	formularios	0001_initial	2026-01-30 02:15:11.778537-06
16	admin	0001_initial	2026-01-30 02:15:11.835799-06
17	admin	0002_logentry_remove_auto_add	2026-01-30 02:15:11.84637-06
18	admin	0003_logentry_add_action_flag_choices	2026-01-30 02:15:11.861128-06
19	formularios	0002_formularioentry_formulario_periodicidad_and_more	2026-01-30 02:15:11.89134-06
20	formularios	0003_alter_paginaversion_options_and_more	2026-01-30 02:15:11.935652-06
21	formularios	0004_paginaversion_index_version	2026-01-30 02:15:11.973353-06
22	formularios	0005_paginaversion_formularios_id_pagi_78e8b2_idx_and_more	2026-01-30 02:15:12.000085-06
23	formularios	0006_remove_paginaversion_formularios_index_v_1e54e0_idx_and_more	2026-01-30 02:15:12.107401-06
24	formularios	0007_fuentedatos_tipo_fuente_and_more	2026-01-30 02:15:12.333616-06
25	formularios	0008_remove_consultasql_columna_label_and_more	2026-01-30 02:15:12.378886-06
28	formularios	0009_userterminal	2026-01-30 02:22:48.842113-06
29	formularios	0010_alter_formularioentry_options_and_more	2026-01-30 02:22:48.881196-06
30	formularios	0011_userterminal_nombre_usuario	2026-01-30 02:22:48.931106-06
31	oauth2_provider	0001_initial	2026-01-30 02:22:59.654768-06
32	oauth2_provider	0002_auto_20190406_1805	2026-01-30 02:22:59.711852-06
33	oauth2_provider	0003_auto_20201211_1314	2026-01-30 02:22:59.75156-06
34	oauth2_provider	0004_auto_20200902_2022	2026-01-30 02:22:59.947653-06
35	oauth2_provider	0005_auto_20211222_2352	2026-01-30 02:23:00.142152-06
36	oauth2_provider	0006_alter_application_client_secret	2026-01-30 02:23:00.263027-06
37	oauth2_provider	0007_application_post_logout_redirect_uris	2026-01-30 02:23:00.303424-06
38	oauth2_provider	0008_alter_accesstoken_token	2026-01-30 02:23:00.342966-06
39	oauth2_provider	0009_add_hash_client_secret	2026-01-30 02:23:00.383312-06
40	oauth2_provider	0010_application_allowed_origins	2026-01-30 02:23:00.559478-06
41	oauth2_provider	0011_refreshtoken_token_family	2026-01-30 02:23:00.588607-06
42	oauth2_provider	0012_add_token_checksum	2026-01-30 02:23:00.764673-06
43	sessions	0001_initial	2026-01-30 02:23:00.783731-06
\.


--
-- TOC entry 5294 (class 0 OID 16970)
-- Dependencies: 265
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5256 (class 0 OID 16452)
-- Dependencies: 227
-- Data for Name: formularios_campo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_campo (id_campo, tipo, clase, nombre_campo, etiqueta, ayuda, config, requerido) FROM stdin;
\.


--
-- TOC entry 5273 (class 0 OID 16546)
-- Dependencies: 244
-- Data for Name: formularios_campo_grupo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_campo_grupo (id, id_campo, id_grupo) FROM stdin;
\.


--
-- TOC entry 5257 (class 0 OID 16459)
-- Dependencies: 228
-- Data for Name: formularios_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_categoria (id, nombre, descripcion) FROM stdin;
\.


--
-- TOC entry 5258 (class 0 OID 16466)
-- Dependencies: 229
-- Data for Name: formularios_clase_campo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_clase_campo (clase, estructura) FROM stdin;
\.


--
-- TOC entry 5280 (class 0 OID 16762)
-- Dependencies: 251
-- Data for Name: formularios_conexion_sql; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_conexion_sql (id, nombre, descripcion, tipo_bd, host, puerto, database, usuario, password_encrypted, activo, fecha_creacion, opciones_extra, creado_por_id) FROM stdin;
\.


--
-- TOC entry 5281 (class 0 OID 16769)
-- Dependencies: 252
-- Data for Name: formularios_consulta_sql; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_consulta_sql (id, nombre, descripcion, query_sql, cache_minutos, ultima_ejecucion, resultado_cache, activo, fecha_creacion, conexion_id, creado_por_id) FROM stdin;
\.


--
-- TOC entry 5265 (class 0 OID 16499)
-- Dependencies: 236
-- Data for Name: formularios_formulario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_formulario (id, nombre, descripcion, permitir_fotos, permitir_gps, disponible_desde_fecha, disponible_hasta_fecha, estado, forma_envio, es_publico, auto_envio, categoria_id, periodicidad) FROM stdin;
\.


--
-- TOC entry 5266 (class 0 OID 16506)
-- Dependencies: 237
-- Data for Name: formularios_formularioindexversion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_formularioindexversion (id_index_version, fecha_creacion) FROM stdin;
\.


--
-- TOC entry 5270 (class 0 OID 16533)
-- Dependencies: 241
-- Data for Name: formularios_formularios_index_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_formularios_index_version (id_index_version, id_formulario) FROM stdin;
\.


--
-- TOC entry 5267 (class 0 OID 16511)
-- Dependencies: 238
-- Data for Name: formularios_fuente_datos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_fuente_datos (id, nombre, descripcion, archivo_nombre, blob_name, blob_url, tipo_archivo, columnas, preview_data, fecha_subida, activo, creado_por_id, tipo_fuente, consulta_sql_id) FROM stdin;
\.


--
-- TOC entry 5271 (class 0 OID 16538)
-- Dependencies: 242
-- Data for Name: formularios_fuente_datos_valor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_fuente_datos_valor (id, columna, key_text, label_text, valor_raw, extras, creado_en, campo_id, fuente_id) FROM stdin;
\.


--
-- TOC entry 5268 (class 0 OID 16518)
-- Dependencies: 239
-- Data for Name: formularios_grupo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_grupo (id_grupo, nombre, id_campo_group) FROM stdin;
\.


--
-- TOC entry 5269 (class 0 OID 16525)
-- Dependencies: 240
-- Data for Name: formularios_pagina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_pagina (id_pagina, secuencia, nombre, descripcion) FROM stdin;
\.


--
-- TOC entry 5277 (class 0 OID 16562)
-- Dependencies: 248
-- Data for Name: formularios_pagina_campo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_pagina_campo (id_campo, sequence, id_pagina_version) FROM stdin;
\.


--
-- TOC entry 5274 (class 0 OID 16551)
-- Dependencies: 245
-- Data for Name: formularios_pagina_index_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_pagina_index_version (id_pagina, id_index_version) FROM stdin;
\.


--
-- TOC entry 5259 (class 0 OID 16473)
-- Dependencies: 230
-- Data for Name: formularios_pagina_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_pagina_version (id_pagina_version, fecha_creacion, id_pagina) FROM stdin;
\.


--
-- TOC entry 5276 (class 0 OID 16557)
-- Dependencies: 247
-- Data for Name: formularios_user_formulario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_user_formulario (id, id_formulario_id, id_usuario_id) FROM stdin;
\.


--
-- TOC entry 5283 (class 0 OID 16812)
-- Dependencies: 254
-- Data for Name: formularios_user_terminal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_user_terminal (id, terminal_info, date, nombre_usuario) FROM stdin;
\.


--
-- TOC entry 5260 (class 0 OID 16478)
-- Dependencies: 231
-- Data for Name: formularios_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_usuario (last_login, nombre_usuario, nombre, correo, password, activo, acceso_web, is_staff, is_superuser) FROM stdin;
\.


--
-- TOC entry 5262 (class 0 OID 16488)
-- Dependencies: 233
-- Data for Name: formularios_usuario_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_usuario_groups (id, usuario_id, group_id) FROM stdin;
\.


--
-- TOC entry 5264 (class 0 OID 16494)
-- Dependencies: 235
-- Data for Name: formularios_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formularios_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5287 (class 0 OID 16837)
-- Dependencies: 258
-- Data for Name: oauth2_provider_accesstoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oauth2_provider_accesstoken (id, token, expires, scope, application_id, user_id, created, updated, source_refresh_token_id, id_token_id, token_checksum) FROM stdin;
\.


--
-- TOC entry 5285 (class 0 OID 16827)
-- Dependencies: 256
-- Data for Name: oauth2_provider_application; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oauth2_provider_application (id, client_id, redirect_uris, client_type, authorization_grant_type, client_secret, name, user_id, skip_authorization, created, updated, algorithm, post_logout_redirect_uris, hash_client_secret, allowed_origins) FROM stdin;
\.


--
-- TOC entry 5289 (class 0 OID 16847)
-- Dependencies: 260
-- Data for Name: oauth2_provider_grant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oauth2_provider_grant (id, code, expires, redirect_uri, scope, application_id, user_id, created, updated, code_challenge, code_challenge_method, nonce, claims) FROM stdin;
\.


--
-- TOC entry 5293 (class 0 OID 16933)
-- Dependencies: 264
-- Data for Name: oauth2_provider_idtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oauth2_provider_idtoken (id, jti, expires, scope, created, updated, application_id, user_id) FROM stdin;
\.


--
-- TOC entry 5291 (class 0 OID 16857)
-- Dependencies: 262
-- Data for Name: oauth2_provider_refreshtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oauth2_provider_refreshtoken (id, token, access_token_id, application_id, user_id, created, updated, revoked, token_family) FROM stdin;
\.


--
-- TOC entry 5300 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5301 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5302 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 120, true);


--
-- TOC entry 5303 (class 0 OID 0)
-- Dependencies: 249
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5304 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 30, true);


--
-- TOC entry 5305 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- TOC entry 5306 (class 0 OID 0)
-- Dependencies: 243
-- Name: formularios_campo_grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formularios_campo_grupo_id_seq', 1, false);


--
-- TOC entry 5307 (class 0 OID 0)
-- Dependencies: 246
-- Name: formularios_user_formulario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formularios_user_formulario_id_seq', 1, false);


--
-- TOC entry 5308 (class 0 OID 0)
-- Dependencies: 253
-- Name: formularios_user_terminal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formularios_user_terminal_id_seq', 1, false);


--
-- TOC entry 5309 (class 0 OID 0)
-- Dependencies: 232
-- Name: formularios_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formularios_usuario_groups_id_seq', 1, false);


--
-- TOC entry 5310 (class 0 OID 0)
-- Dependencies: 234
-- Name: formularios_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formularios_usuario_user_permissions_id_seq', 1, false);


--
-- TOC entry 5311 (class 0 OID 0)
-- Dependencies: 257
-- Name: oauth2_provider_accesstoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oauth2_provider_accesstoken_id_seq', 1, false);


--
-- TOC entry 5312 (class 0 OID 0)
-- Dependencies: 255
-- Name: oauth2_provider_application_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oauth2_provider_application_id_seq', 1, false);


--
-- TOC entry 5313 (class 0 OID 0)
-- Dependencies: 259
-- Name: oauth2_provider_grant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oauth2_provider_grant_id_seq', 1, false);


--
-- TOC entry 5314 (class 0 OID 0)
-- Dependencies: 263
-- Name: oauth2_provider_idtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oauth2_provider_idtoken_id_seq', 1, false);


--
-- TOC entry 5315 (class 0 OID 0)
-- Dependencies: 261
-- Name: oauth2_provider_refreshtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oauth2_provider_refreshtoken_id_seq', 1, false);


--
-- TOC entry 4901 (class 2606 OID 16450)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4906 (class 2606 OID 16436)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4909 (class 2606 OID 16425)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 16417)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 16427)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4898 (class 2606 OID 16411)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4994 (class 2606 OID 16728)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4891 (class 2606 OID 16405)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4893 (class 2606 OID 16403)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 16397)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5057 (class 2606 OID 16976)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4972 (class 2606 OID 16666)
-- Name: formularios_campo_grupo formularios_campo_grupo_id_grupo_id_campo_3f10fa8b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_campo_grupo
    ADD CONSTRAINT formularios_campo_grupo_id_grupo_id_campo_3f10fa8b_uniq UNIQUE (id_grupo, id_campo);


--
-- TOC entry 4974 (class 2606 OID 16550)
-- Name: formularios_campo_grupo formularios_campo_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_campo_grupo
    ADD CONSTRAINT formularios_campo_grupo_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 16458)
-- Name: formularios_campo formularios_campo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_campo
    ADD CONSTRAINT formularios_campo_pkey PRIMARY KEY (id_campo);


--
-- TOC entry 4913 (class 2606 OID 16465)
-- Name: formularios_categoria formularios_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_categoria
    ADD CONSTRAINT formularios_categoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4916 (class 2606 OID 16472)
-- Name: formularios_clase_campo formularios_clase_campo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_clase_campo
    ADD CONSTRAINT formularios_clase_campo_pkey PRIMARY KEY (clase);


--
-- TOC entry 5000 (class 2606 OID 16768)
-- Name: formularios_conexion_sql formularios_conexion_sql_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_conexion_sql
    ADD CONSTRAINT formularios_conexion_sql_pkey PRIMARY KEY (id);


--
-- TOC entry 5005 (class 2606 OID 16775)
-- Name: formularios_consulta_sql formularios_consulta_sql_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_consulta_sql
    ADD CONSTRAINT formularios_consulta_sql_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 16505)
-- Name: formularios_formulario formularios_formulario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formulario
    ADD CONSTRAINT formularios_formulario_pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 16510)
-- Name: formularios_formularioindexversion formularios_formularioindexversion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formularioindexversion
    ADD CONSTRAINT formularios_formularioindexversion_pkey PRIMARY KEY (id_index_version);


--
-- TOC entry 4960 (class 2606 OID 16537)
-- Name: formularios_formularios_index_version formularios_formularios_index_version_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formularios_index_version
    ADD CONSTRAINT formularios_formularios_index_version_pkey PRIMARY KEY (id_index_version);


--
-- TOC entry 4951 (class 2606 OID 16517)
-- Name: formularios_fuente_datos formularios_fuente_datos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos
    ADD CONSTRAINT formularios_fuente_datos_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 16650)
-- Name: formularios_fuente_datos_valor formularios_fuente_datos_valor_campo_id_key_text_8e0934f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos_valor
    ADD CONSTRAINT formularios_fuente_datos_valor_campo_id_key_text_8e0934f7_uniq UNIQUE (campo_id, key_text);


--
-- TOC entry 4968 (class 2606 OID 16544)
-- Name: formularios_fuente_datos_valor formularios_fuente_datos_valor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos_valor
    ADD CONSTRAINT formularios_fuente_datos_valor_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 16524)
-- Name: formularios_grupo formularios_grupo_id_campo_group_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_grupo
    ADD CONSTRAINT formularios_grupo_id_campo_group_key UNIQUE (id_campo_group);


--
-- TOC entry 4955 (class 2606 OID 16522)
-- Name: formularios_grupo formularios_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_grupo
    ADD CONSTRAINT formularios_grupo_pkey PRIMARY KEY (id_grupo);


--
-- TOC entry 4987 (class 2606 OID 16707)
-- Name: formularios_pagina_campo formularios_pagina_campo_id_campo_id_pagina_versi_bad4d405_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_campo
    ADD CONSTRAINT formularios_pagina_campo_id_campo_id_pagina_versi_bad4d405_uniq UNIQUE (id_campo, id_pagina_version);


--
-- TOC entry 4991 (class 2606 OID 16567)
-- Name: formularios_pagina_campo formularios_pagina_campo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_campo
    ADD CONSTRAINT formularios_pagina_campo_pkey PRIMARY KEY (id_campo);


--
-- TOC entry 4977 (class 2606 OID 16555)
-- Name: formularios_pagina_index_version formularios_pagina_index_version_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_index_version
    ADD CONSTRAINT formularios_pagina_index_version_pkey PRIMARY KEY (id_pagina);


--
-- TOC entry 4957 (class 2606 OID 16532)
-- Name: formularios_pagina formularios_pagina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina
    ADD CONSTRAINT formularios_pagina_pkey PRIMARY KEY (id_pagina);


--
-- TOC entry 4921 (class 2606 OID 16477)
-- Name: formularios_pagina_version formularios_pagina_version_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_version
    ADD CONSTRAINT formularios_pagina_version_pkey PRIMARY KEY (id_pagina_version);


--
-- TOC entry 4980 (class 2606 OID 16691)
-- Name: formularios_user_formulario formularios_user_formula_id_formulario_id_id_usua_75d33c88_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_formulario
    ADD CONSTRAINT formularios_user_formula_id_formulario_id_id_usua_75d33c88_uniq UNIQUE (id_formulario_id, id_usuario_id);


--
-- TOC entry 4985 (class 2606 OID 16561)
-- Name: formularios_user_formulario formularios_user_formulario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_formulario
    ADD CONSTRAINT formularios_user_formulario_pkey PRIMARY KEY (id);


--
-- TOC entry 5009 (class 2606 OID 16818)
-- Name: formularios_user_terminal formularios_user_terminal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_terminal
    ADD CONSTRAINT formularios_user_terminal_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 16486)
-- Name: formularios_usuario formularios_usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario
    ADD CONSTRAINT formularios_usuario_correo_key UNIQUE (correo);


--
-- TOC entry 4930 (class 2606 OID 16492)
-- Name: formularios_usuario_groups formularios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_groups
    ADD CONSTRAINT formularios_usuario_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 16573)
-- Name: formularios_usuario_groups formularios_usuario_groups_usuario_id_group_id_9443b0e1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_groups
    ADD CONSTRAINT formularios_usuario_groups_usuario_id_group_id_9443b0e1_uniq UNIQUE (usuario_id, group_id);


--
-- TOC entry 4927 (class 2606 OID 16484)
-- Name: formularios_usuario formularios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario
    ADD CONSTRAINT formularios_usuario_pkey PRIMARY KEY (nombre_usuario);


--
-- TOC entry 4937 (class 2606 OID 16498)
-- Name: formularios_usuario_user_permissions formularios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_user_permissions
    ADD CONSTRAINT formularios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4941 (class 2606 OID 16588)
-- Name: formularios_usuario_user_permissions formularios_usuario_user_usuario_id_permission_id_1403bb32_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_user_permissions
    ADD CONSTRAINT formularios_usuario_user_usuario_id_permission_id_1403bb32_uniq UNIQUE (usuario_id, permission_id);


--
-- TOC entry 5021 (class 2606 OID 16943)
-- Name: oauth2_provider_accesstoken oauth2_provider_accesstoken_id_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_accesstoken_id_token_id_key UNIQUE (id_token_id);


--
-- TOC entry 5023 (class 2606 OID 16843)
-- Name: oauth2_provider_accesstoken oauth2_provider_accesstoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_accesstoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 16865)
-- Name: oauth2_provider_accesstoken oauth2_provider_accesstoken_source_refresh_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_accesstoken_source_refresh_token_id_key UNIQUE (source_refresh_token_id);


--
-- TOC entry 5028 (class 2606 OID 16968)
-- Name: oauth2_provider_accesstoken oauth2_provider_accesstoken_token_checksum_85319a26_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_accesstoken_token_checksum_85319a26_uniq UNIQUE (token_checksum);


--
-- TOC entry 5012 (class 2606 OID 16835)
-- Name: oauth2_provider_application oauth2_provider_application_client_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_application
    ADD CONSTRAINT oauth2_provider_application_client_id_key UNIQUE (client_id);


--
-- TOC entry 5016 (class 2606 OID 16833)
-- Name: oauth2_provider_application oauth2_provider_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_application
    ADD CONSTRAINT oauth2_provider_application_pkey PRIMARY KEY (id);


--
-- TOC entry 5034 (class 2606 OID 16855)
-- Name: oauth2_provider_grant oauth2_provider_grant_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_grant
    ADD CONSTRAINT oauth2_provider_grant_code_key UNIQUE (code);


--
-- TOC entry 5036 (class 2606 OID 16853)
-- Name: oauth2_provider_grant oauth2_provider_grant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_grant
    ADD CONSTRAINT oauth2_provider_grant_pkey PRIMARY KEY (id);


--
-- TOC entry 5050 (class 2606 OID 16941)
-- Name: oauth2_provider_idtoken oauth2_provider_idtoken_jti_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_idtoken
    ADD CONSTRAINT oauth2_provider_idtoken_jti_key UNIQUE (jti);


--
-- TOC entry 5052 (class 2606 OID 16939)
-- Name: oauth2_provider_idtoken oauth2_provider_idtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_idtoken
    ADD CONSTRAINT oauth2_provider_idtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5040 (class 2606 OID 16863)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refreshtoken_access_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refreshtoken_access_token_id_key UNIQUE (access_token_id);


--
-- TOC entry 5043 (class 2606 OID 16861)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refreshtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refreshtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5045 (class 2606 OID 16910)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refreshtoken_token_revoked_af8a5134_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refreshtoken_token_revoked_af8a5134_uniq UNIQUE (token, revoked);


--
-- TOC entry 4899 (class 1259 OID 16451)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4904 (class 1259 OID 16447)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4907 (class 1259 OID 16448)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4894 (class 1259 OID 16433)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4992 (class 1259 OID 16739)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4995 (class 1259 OID 16740)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4996 (class 1259 OID 16741)
-- Name: django_admin_log_user_id_c564eba6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6_like ON public.django_admin_log USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5055 (class 1259 OID 16978)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5058 (class 1259 OID 16977)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4969 (class 1259 OID 16677)
-- Name: formularios_campo_grupo_id_campo_13b94d4f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_campo_grupo_id_campo_13b94d4f ON public.formularios_campo_grupo USING btree (id_campo);


--
-- TOC entry 4970 (class 1259 OID 16678)
-- Name: formularios_campo_grupo_id_grupo_964ab96e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_campo_grupo_id_grupo_964ab96e ON public.formularios_campo_grupo USING btree (id_grupo);


--
-- TOC entry 4961 (class 1259 OID 16663)
-- Name: formularios_campo_i_254189_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_campo_i_254189_idx ON public.formularios_fuente_datos_valor USING btree (campo_id, label_text);


--
-- TOC entry 4962 (class 1259 OID 16664)
-- Name: formularios_campo_i_4d9317_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_campo_i_4d9317_idx ON public.formularios_fuente_datos_valor USING btree (campo_id, key_text);


--
-- TOC entry 4914 (class 1259 OID 16568)
-- Name: formularios_clase_campo_clase_583268a3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_clase_campo_clase_583268a3_like ON public.formularios_clase_campo USING btree (clase varchar_pattern_ops);


--
-- TOC entry 4997 (class 1259 OID 16786)
-- Name: formularios_conexion_sql_creado_por_id_8c2bcd71; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_conexion_sql_creado_por_id_8c2bcd71 ON public.formularios_conexion_sql USING btree (creado_por_id);


--
-- TOC entry 4998 (class 1259 OID 16787)
-- Name: formularios_conexion_sql_creado_por_id_8c2bcd71_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_conexion_sql_creado_por_id_8c2bcd71_like ON public.formularios_conexion_sql USING btree (creado_por_id varchar_pattern_ops);


--
-- TOC entry 5001 (class 1259 OID 16798)
-- Name: formularios_consulta_sql_conexion_id_2a63507d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_consulta_sql_conexion_id_2a63507d ON public.formularios_consulta_sql USING btree (conexion_id);


--
-- TOC entry 5002 (class 1259 OID 16799)
-- Name: formularios_consulta_sql_creado_por_id_be25a743; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_consulta_sql_creado_por_id_be25a743 ON public.formularios_consulta_sql USING btree (creado_por_id);


--
-- TOC entry 5003 (class 1259 OID 16800)
-- Name: formularios_consulta_sql_creado_por_id_be25a743_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_consulta_sql_creado_por_id_be25a743_like ON public.formularios_consulta_sql USING btree (creado_por_id varchar_pattern_ops);


--
-- TOC entry 4942 (class 1259 OID 16607)
-- Name: formularios_formulario_categoria_id_01bd3ee9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_formulario_categoria_id_01bd3ee9 ON public.formularios_formulario USING btree (categoria_id);


--
-- TOC entry 4958 (class 1259 OID 16648)
-- Name: formularios_formularios_index_version_id_formulario_d0a77691; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_formularios_index_version_id_formulario_d0a77691 ON public.formularios_formularios_index_version USING btree (id_formulario);


--
-- TOC entry 4947 (class 1259 OID 16801)
-- Name: formularios_fuente_datos_consulta_sql_id_1bc0cfd0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_fuente_datos_consulta_sql_id_1bc0cfd0 ON public.formularios_fuente_datos USING btree (consulta_sql_id);


--
-- TOC entry 4948 (class 1259 OID 16619)
-- Name: formularios_fuente_datos_creado_por_id_d51268af; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_fuente_datos_creado_por_id_d51268af ON public.formularios_fuente_datos USING btree (creado_por_id);


--
-- TOC entry 4949 (class 1259 OID 16620)
-- Name: formularios_fuente_datos_creado_por_id_d51268af_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_fuente_datos_creado_por_id_d51268af_like ON public.formularios_fuente_datos USING btree (creado_por_id varchar_pattern_ops);


--
-- TOC entry 4963 (class 1259 OID 16661)
-- Name: formularios_fuente_datos_valor_campo_id_845763f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_fuente_datos_valor_campo_id_845763f2 ON public.formularios_fuente_datos_valor USING btree (campo_id);


--
-- TOC entry 4966 (class 1259 OID 16662)
-- Name: formularios_fuente_datos_valor_fuente_id_d2de8f3f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_fuente_datos_valor_fuente_id_d2de8f3f ON public.formularios_fuente_datos_valor USING btree (fuente_id);


--
-- TOC entry 4917 (class 1259 OID 16759)
-- Name: formularios_id_pagi_78e8b2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_id_pagi_78e8b2_idx ON public.formularios_pagina_version USING btree (id_pagina, fecha_creacion DESC);


--
-- TOC entry 4978 (class 1259 OID 16705)
-- Name: formularios_id_usua_73941f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_id_usua_73941f_idx ON public.formularios_user_formulario USING btree (id_usuario_id, id_formulario_id);


--
-- TOC entry 4988 (class 1259 OID 16718)
-- Name: formularios_pagina_campo_id_pagina_version_dbea0a3d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_pagina_campo_id_pagina_version_dbea0a3d ON public.formularios_pagina_campo USING btree (id_pagina_version);


--
-- TOC entry 4989 (class 1259 OID 16719)
-- Name: formularios_pagina_campo_id_pagina_version_dbea0a3d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_pagina_campo_id_pagina_version_dbea0a3d_like ON public.formularios_pagina_campo USING btree (id_pagina_version varchar_pattern_ops);


--
-- TOC entry 4975 (class 1259 OID 16689)
-- Name: formularios_pagina_index_version_id_index_version_4bafe97f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_pagina_index_version_id_index_version_4bafe97f ON public.formularios_pagina_index_version USING btree (id_index_version);


--
-- TOC entry 4918 (class 1259 OID 16747)
-- Name: formularios_pagina_version_id_pagina_13267a50; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_pagina_version_id_pagina_13267a50 ON public.formularios_pagina_version USING btree (id_pagina);


--
-- TOC entry 4919 (class 1259 OID 16569)
-- Name: formularios_pagina_version_id_pagina_version_078312aa_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_pagina_version_id_pagina_version_078312aa_like ON public.formularios_pagina_version USING btree (id_pagina_version varchar_pattern_ops);


--
-- TOC entry 4981 (class 1259 OID 16702)
-- Name: formularios_user_formulario_id_formulario_id_625621e0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_user_formulario_id_formulario_id_625621e0 ON public.formularios_user_formulario USING btree (id_formulario_id);


--
-- TOC entry 4982 (class 1259 OID 16703)
-- Name: formularios_user_formulario_id_usuario_id_3f549cb5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_user_formulario_id_usuario_id_3f549cb5 ON public.formularios_user_formulario USING btree (id_usuario_id);


--
-- TOC entry 4983 (class 1259 OID 16704)
-- Name: formularios_user_formulario_id_usuario_id_3f549cb5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_user_formulario_id_usuario_id_3f549cb5_like ON public.formularios_user_formulario USING btree (id_usuario_id varchar_pattern_ops);


--
-- TOC entry 5006 (class 1259 OID 16824)
-- Name: formularios_user_terminal_nombre_usuario_30d4fec7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_user_terminal_nombre_usuario_30d4fec7 ON public.formularios_user_terminal USING btree (nombre_usuario);


--
-- TOC entry 5007 (class 1259 OID 16825)
-- Name: formularios_user_terminal_nombre_usuario_30d4fec7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_user_terminal_nombre_usuario_30d4fec7_like ON public.formularios_user_terminal USING btree (nombre_usuario varchar_pattern_ops);


--
-- TOC entry 4922 (class 1259 OID 16571)
-- Name: formularios_usuario_correo_8ac38a5b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_correo_8ac38a5b_like ON public.formularios_usuario USING btree (correo varchar_pattern_ops);


--
-- TOC entry 4928 (class 1259 OID 16586)
-- Name: formularios_usuario_groups_group_id_59261c95; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_groups_group_id_59261c95 ON public.formularios_usuario_groups USING btree (group_id);


--
-- TOC entry 4931 (class 1259 OID 16584)
-- Name: formularios_usuario_groups_usuario_id_dc265385; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_groups_usuario_id_dc265385 ON public.formularios_usuario_groups USING btree (usuario_id);


--
-- TOC entry 4932 (class 1259 OID 16585)
-- Name: formularios_usuario_groups_usuario_id_dc265385_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_groups_usuario_id_dc265385_like ON public.formularios_usuario_groups USING btree (usuario_id varchar_pattern_ops);


--
-- TOC entry 4925 (class 1259 OID 16570)
-- Name: formularios_usuario_nombre_usuario_f9b1e930_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_nombre_usuario_f9b1e930_like ON public.formularios_usuario USING btree (nombre_usuario varchar_pattern_ops);


--
-- TOC entry 4935 (class 1259 OID 16601)
-- Name: formularios_usuario_user_permissions_permission_id_cb4c324e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_user_permissions_permission_id_cb4c324e ON public.formularios_usuario_user_permissions USING btree (permission_id);


--
-- TOC entry 4938 (class 1259 OID 16599)
-- Name: formularios_usuario_user_permissions_usuario_id_f63bbbfb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_user_permissions_usuario_id_f63bbbfb ON public.formularios_usuario_user_permissions USING btree (usuario_id);


--
-- TOC entry 4939 (class 1259 OID 16600)
-- Name: formularios_usuario_user_permissions_usuario_id_f63bbbfb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX formularios_usuario_user_permissions_usuario_id_f63bbbfb_like ON public.formularios_usuario_user_permissions USING btree (usuario_id varchar_pattern_ops);


--
-- TOC entry 5019 (class 1259 OID 16892)
-- Name: oauth2_provider_accesstoken_application_id_b22886e1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_accesstoken_application_id_b22886e1 ON public.oauth2_provider_accesstoken USING btree (application_id);


--
-- TOC entry 5026 (class 1259 OID 16969)
-- Name: oauth2_provider_accesstoken_token_checksum_85319a26_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_accesstoken_token_checksum_85319a26_like ON public.oauth2_provider_accesstoken USING btree (token_checksum varchar_pattern_ops);


--
-- TOC entry 5029 (class 1259 OID 16893)
-- Name: oauth2_provider_accesstoken_user_id_6e4c9a65; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_accesstoken_user_id_6e4c9a65 ON public.oauth2_provider_accesstoken USING btree (user_id);


--
-- TOC entry 5030 (class 1259 OID 16894)
-- Name: oauth2_provider_accesstoken_user_id_6e4c9a65_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_accesstoken_user_id_6e4c9a65_like ON public.oauth2_provider_accesstoken USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5010 (class 1259 OID 16876)
-- Name: oauth2_provider_application_client_id_03f0cc84_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_application_client_id_03f0cc84_like ON public.oauth2_provider_application USING btree (client_id varchar_pattern_ops);


--
-- TOC entry 5013 (class 1259 OID 16877)
-- Name: oauth2_provider_application_client_secret_53133678; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_application_client_secret_53133678 ON public.oauth2_provider_application USING btree (client_secret);


--
-- TOC entry 5014 (class 1259 OID 16878)
-- Name: oauth2_provider_application_client_secret_53133678_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_application_client_secret_53133678_like ON public.oauth2_provider_application USING btree (client_secret varchar_pattern_ops);


--
-- TOC entry 5017 (class 1259 OID 16879)
-- Name: oauth2_provider_application_user_id_79829054; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_application_user_id_79829054 ON public.oauth2_provider_application USING btree (user_id);


--
-- TOC entry 5018 (class 1259 OID 16880)
-- Name: oauth2_provider_application_user_id_79829054_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_application_user_id_79829054_like ON public.oauth2_provider_application USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5031 (class 1259 OID 16906)
-- Name: oauth2_provider_grant_application_id_81923564; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_grant_application_id_81923564 ON public.oauth2_provider_grant USING btree (application_id);


--
-- TOC entry 5032 (class 1259 OID 16905)
-- Name: oauth2_provider_grant_code_49ab4ddf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_grant_code_49ab4ddf_like ON public.oauth2_provider_grant USING btree (code varchar_pattern_ops);


--
-- TOC entry 5037 (class 1259 OID 16907)
-- Name: oauth2_provider_grant_user_id_e8f62af8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_grant_user_id_e8f62af8 ON public.oauth2_provider_grant USING btree (user_id);


--
-- TOC entry 5038 (class 1259 OID 16908)
-- Name: oauth2_provider_grant_user_id_e8f62af8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_grant_user_id_e8f62af8_like ON public.oauth2_provider_grant USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5048 (class 1259 OID 16961)
-- Name: oauth2_provider_idtoken_application_id_08c5ff4f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_idtoken_application_id_08c5ff4f ON public.oauth2_provider_idtoken USING btree (application_id);


--
-- TOC entry 5053 (class 1259 OID 16962)
-- Name: oauth2_provider_idtoken_user_id_dd512b59; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_idtoken_user_id_dd512b59 ON public.oauth2_provider_idtoken USING btree (user_id);


--
-- TOC entry 5054 (class 1259 OID 16963)
-- Name: oauth2_provider_idtoken_user_id_dd512b59_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_idtoken_user_id_dd512b59_like ON public.oauth2_provider_idtoken USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5041 (class 1259 OID 16926)
-- Name: oauth2_provider_refreshtoken_application_id_2d1c311b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_refreshtoken_application_id_2d1c311b ON public.oauth2_provider_refreshtoken USING btree (application_id);


--
-- TOC entry 5046 (class 1259 OID 16927)
-- Name: oauth2_provider_refreshtoken_user_id_da837fce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_refreshtoken_user_id_da837fce ON public.oauth2_provider_refreshtoken USING btree (user_id);


--
-- TOC entry 5047 (class 1259 OID 16928)
-- Name: oauth2_provider_refreshtoken_user_id_da837fce_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX oauth2_provider_refreshtoken_user_id_da837fce_like ON public.oauth2_provider_refreshtoken USING btree (user_id varchar_pattern_ops);


--
-- TOC entry 5060 (class 2606 OID 16442)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5061 (class 2606 OID 16437)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5059 (class 2606 OID 16428)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5083 (class 2606 OID 16729)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5084 (class 2606 OID 16734)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5075 (class 2606 OID 16667)
-- Name: formularios_campo_grupo formularios_campo_gr_id_campo_13b94d4f_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_campo_grupo
    ADD CONSTRAINT formularios_campo_gr_id_campo_13b94d4f_fk_formulari FOREIGN KEY (id_campo) REFERENCES public.formularios_campo(id_campo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5076 (class 2606 OID 16672)
-- Name: formularios_campo_grupo formularios_campo_gr_id_grupo_964ab96e_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_campo_grupo
    ADD CONSTRAINT formularios_campo_gr_id_grupo_964ab96e_fk_formulari FOREIGN KEY (id_grupo) REFERENCES public.formularios_grupo(id_grupo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5085 (class 2606 OID 16781)
-- Name: formularios_conexion_sql formularios_conexion_creado_por_id_8c2bcd71_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_conexion_sql
    ADD CONSTRAINT formularios_conexion_creado_por_id_8c2bcd71_fk_formulari FOREIGN KEY (creado_por_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5086 (class 2606 OID 16788)
-- Name: formularios_consulta_sql formularios_consulta_conexion_id_2a63507d_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_consulta_sql
    ADD CONSTRAINT formularios_consulta_conexion_id_2a63507d_fk_formulari FOREIGN KEY (conexion_id) REFERENCES public.formularios_conexion_sql(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5087 (class 2606 OID 16793)
-- Name: formularios_consulta_sql formularios_consulta_creado_por_id_be25a743_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_consulta_sql
    ADD CONSTRAINT formularios_consulta_creado_por_id_be25a743_fk_formulari FOREIGN KEY (creado_por_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5067 (class 2606 OID 16602)
-- Name: formularios_formulario formularios_formular_categoria_id_01bd3ee9_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formulario
    ADD CONSTRAINT formularios_formular_categoria_id_01bd3ee9_fk_formulari FOREIGN KEY (categoria_id) REFERENCES public.formularios_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5071 (class 2606 OID 16643)
-- Name: formularios_formularios_index_version formularios_formular_id_formulario_d0a77691_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formularios_index_version
    ADD CONSTRAINT formularios_formular_id_formulario_d0a77691_fk_formulari FOREIGN KEY (id_formulario) REFERENCES public.formularios_formulario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5072 (class 2606 OID 16638)
-- Name: formularios_formularios_index_version formularios_formular_id_index_version_e3b321ce_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_formularios_index_version
    ADD CONSTRAINT formularios_formular_id_index_version_e3b321ce_fk_formulari FOREIGN KEY (id_index_version) REFERENCES public.formularios_formularioindexversion(id_index_version) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5073 (class 2606 OID 16651)
-- Name: formularios_fuente_datos_valor formularios_fuente_d_campo_id_845763f2_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos_valor
    ADD CONSTRAINT formularios_fuente_d_campo_id_845763f2_fk_formulari FOREIGN KEY (campo_id) REFERENCES public.formularios_campo(id_campo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5068 (class 2606 OID 16776)
-- Name: formularios_fuente_datos formularios_fuente_d_consulta_sql_id_1bc0cfd0_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos
    ADD CONSTRAINT formularios_fuente_d_consulta_sql_id_1bc0cfd0_fk_formulari FOREIGN KEY (consulta_sql_id) REFERENCES public.formularios_consulta_sql(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5069 (class 2606 OID 16614)
-- Name: formularios_fuente_datos formularios_fuente_d_creado_por_id_d51268af_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos
    ADD CONSTRAINT formularios_fuente_d_creado_por_id_d51268af_fk_formulari FOREIGN KEY (creado_por_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5074 (class 2606 OID 16656)
-- Name: formularios_fuente_datos_valor formularios_fuente_d_fuente_id_d2de8f3f_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_fuente_datos_valor
    ADD CONSTRAINT formularios_fuente_d_fuente_id_d2de8f3f_fk_formulari FOREIGN KEY (fuente_id) REFERENCES public.formularios_fuente_datos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5070 (class 2606 OID 16621)
-- Name: formularios_grupo formularios_grupo_id_campo_group_fba9dbb9_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_grupo
    ADD CONSTRAINT formularios_grupo_id_campo_group_fba9dbb9_fk_formulari FOREIGN KEY (id_campo_group) REFERENCES public.formularios_campo(id_campo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5081 (class 2606 OID 16708)
-- Name: formularios_pagina_campo formularios_pagina_c_id_campo_32cb62da_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_campo
    ADD CONSTRAINT formularios_pagina_c_id_campo_32cb62da_fk_formulari FOREIGN KEY (id_campo) REFERENCES public.formularios_campo(id_campo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5082 (class 2606 OID 16713)
-- Name: formularios_pagina_campo formularios_pagina_c_id_pagina_version_dbea0a3d_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_campo
    ADD CONSTRAINT formularios_pagina_c_id_pagina_version_dbea0a3d_fk_formulari FOREIGN KEY (id_pagina_version) REFERENCES public.formularios_pagina_version(id_pagina_version) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5077 (class 2606 OID 16684)
-- Name: formularios_pagina_index_version formularios_pagina_i_id_index_version_4bafe97f_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_index_version
    ADD CONSTRAINT formularios_pagina_i_id_index_version_4bafe97f_fk_formulari FOREIGN KEY (id_index_version) REFERENCES public.formularios_formularioindexversion(id_index_version) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5078 (class 2606 OID 16679)
-- Name: formularios_pagina_index_version formularios_pagina_i_id_pagina_2cbac61f_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_index_version
    ADD CONSTRAINT formularios_pagina_i_id_pagina_2cbac61f_fk_formulari FOREIGN KEY (id_pagina) REFERENCES public.formularios_pagina(id_pagina) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5062 (class 2606 OID 16748)
-- Name: formularios_pagina_version formularios_pagina_v_id_pagina_13267a50_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_pagina_version
    ADD CONSTRAINT formularios_pagina_v_id_pagina_13267a50_fk_formulari FOREIGN KEY (id_pagina) REFERENCES public.formularios_pagina(id_pagina) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5079 (class 2606 OID 16692)
-- Name: formularios_user_formulario formularios_user_for_id_formulario_id_625621e0_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_formulario
    ADD CONSTRAINT formularios_user_for_id_formulario_id_625621e0_fk_formulari FOREIGN KEY (id_formulario_id) REFERENCES public.formularios_formulario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5080 (class 2606 OID 16697)
-- Name: formularios_user_formulario formularios_user_for_id_usuario_id_3f549cb5_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_formulario
    ADD CONSTRAINT formularios_user_for_id_usuario_id_3f549cb5_fk_formulari FOREIGN KEY (id_usuario_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5088 (class 2606 OID 16819)
-- Name: formularios_user_terminal formularios_user_ter_nombre_usuario_30d4fec7_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_user_terminal
    ADD CONSTRAINT formularios_user_ter_nombre_usuario_30d4fec7_fk_formulari FOREIGN KEY (nombre_usuario) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5065 (class 2606 OID 16594)
-- Name: formularios_usuario_user_permissions formularios_usuario__permission_id_cb4c324e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_user_permissions
    ADD CONSTRAINT formularios_usuario__permission_id_cb4c324e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5063 (class 2606 OID 16574)
-- Name: formularios_usuario_groups formularios_usuario__usuario_id_dc265385_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_groups
    ADD CONSTRAINT formularios_usuario__usuario_id_dc265385_fk_formulari FOREIGN KEY (usuario_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5066 (class 2606 OID 16589)
-- Name: formularios_usuario_user_permissions formularios_usuario__usuario_id_f63bbbfb_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_user_permissions
    ADD CONSTRAINT formularios_usuario__usuario_id_f63bbbfb_fk_formulari FOREIGN KEY (usuario_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5064 (class 2606 OID 16579)
-- Name: formularios_usuario_groups formularios_usuario_groups_group_id_59261c95_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formularios_usuario_groups
    ADD CONSTRAINT formularios_usuario_groups_group_id_59261c95_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5090 (class 2606 OID 16881)
-- Name: oauth2_provider_accesstoken oauth2_provider_acce_application_id_b22886e1_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_acce_application_id_b22886e1_fk_oauth2_pr FOREIGN KEY (application_id) REFERENCES public.oauth2_provider_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5091 (class 2606 OID 16944)
-- Name: oauth2_provider_accesstoken oauth2_provider_acce_id_token_id_85db651b_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_acce_id_token_id_85db651b_fk_oauth2_pr FOREIGN KEY (id_token_id) REFERENCES public.oauth2_provider_idtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5092 (class 2606 OID 16866)
-- Name: oauth2_provider_accesstoken oauth2_provider_acce_source_refresh_token_e66fbc72_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_acce_source_refresh_token_e66fbc72_fk_oauth2_pr FOREIGN KEY (source_refresh_token_id) REFERENCES public.oauth2_provider_refreshtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5093 (class 2606 OID 16886)
-- Name: oauth2_provider_accesstoken oauth2_provider_acce_user_id_6e4c9a65_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_accesstoken
    ADD CONSTRAINT oauth2_provider_acce_user_id_6e4c9a65_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5089 (class 2606 OID 16871)
-- Name: oauth2_provider_application oauth2_provider_appl_user_id_79829054_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_application
    ADD CONSTRAINT oauth2_provider_appl_user_id_79829054_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5094 (class 2606 OID 16895)
-- Name: oauth2_provider_grant oauth2_provider_gran_application_id_81923564_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_grant
    ADD CONSTRAINT oauth2_provider_gran_application_id_81923564_fk_oauth2_pr FOREIGN KEY (application_id) REFERENCES public.oauth2_provider_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5095 (class 2606 OID 16900)
-- Name: oauth2_provider_grant oauth2_provider_gran_user_id_e8f62af8_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_grant
    ADD CONSTRAINT oauth2_provider_gran_user_id_e8f62af8_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5099 (class 2606 OID 16951)
-- Name: oauth2_provider_idtoken oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_idtoken
    ADD CONSTRAINT oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr FOREIGN KEY (application_id) REFERENCES public.oauth2_provider_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5100 (class 2606 OID 16956)
-- Name: oauth2_provider_idtoken oauth2_provider_idto_user_id_dd512b59_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_idtoken
    ADD CONSTRAINT oauth2_provider_idto_user_id_dd512b59_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5096 (class 2606 OID 16911)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr FOREIGN KEY (access_token_id) REFERENCES public.oauth2_provider_accesstoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5097 (class 2606 OID 16916)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refr_application_id_2d1c311b_fk_oauth2_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refr_application_id_2d1c311b_fk_oauth2_pr FOREIGN KEY (application_id) REFERENCES public.oauth2_provider_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5098 (class 2606 OID 16921)
-- Name: oauth2_provider_refreshtoken oauth2_provider_refr_user_id_da837fce_fk_formulari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth2_provider_refreshtoken
    ADD CONSTRAINT oauth2_provider_refr_user_id_da837fce_fk_formulari FOREIGN KEY (user_id) REFERENCES public.formularios_usuario(nombre_usuario) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-01-29 23:06:47

--
-- PostgreSQL database dump complete
--

